import logging
import json
from pathlib import Path
import networkx as nx
import matplotlib.pyplot as plt
import time

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

def generate_dmca_report(clip_tag: str, verdict: str, source_id: str, output_dir: Path) -> str:
    """
    Generates a formal DMCA Takedown Notice text file.
    Returns the path to the generated report.
    """
    report_content = f"""
============================================================
DIGITAL MILLENNIUM COPYRIGHT ACT (DMCA) NOTICE
============================================================
Date: {time.strftime("%Y-%m-%d")}
Generated By: GuardianStream Automated Enforcement System

INFRINGEMENT DETAILS:
---------------------
Content ID      : {clip_tag}
Verification    : {verdict}
Traced Source   : {source_id}

EVIDENCE SUMMARY:
-----------------
1. Perceptual Hash Match: Confirmed (>95% similarity)
2. Forensic Watermark   : Extracted ID '{source_id}'
3. AI Context Analysis  : Verified as Unauthorized/Fake

LEGAL DEMAND:
-------------
Pursuant to 17 U.S.C. § 512(c)(3), we demand the immediate:
1. Removal of the infringing content.
2. Disabling of access to the content.
3. Termination of repeat infringer accounts associated with '{source_id}'.

This is an automated legal notice. Failure to comply may result in further legal action.
============================================================
"""
    
    # Ensure directory exists
    output_dir.mkdir(parents=True, exist_ok=True)
    report_file = output_dir / f"DMCA_{clip_tag}.txt"
    
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(report_content)
    
    logger.info(f"📄 DMCA Report generated: {report_file.name}")
    return str(report_file)

def simulate_propagation_graph(original_clip: str, pirated_clips: list, output_dir: Path) -> str:
    """
    Creates a visual graph showing the path of content leakage.
    Returns the path to the saved image.
    """
    logger.info("📊 Generating Content Propagation Graph...")
    
    G = nx.DiGraph()
    
    # Add Nodes
    G.add_node("Original Source", type="official", time="T=0")
    
    for i, clip in enumerate(pirated_clips):
        platform = clip.get("platform", "Unknown")
        node_name = f"{platform}_Leak_{i}"
        G.add_node(node_name, type="piracy", time=f"T+{i*15}m")
        
    # Add Edges (Chain reaction)
    for i in range(len(pirated_clips)):
        if i == 0:
            G.add_edge("Original Source", f"{pirated_clips[i]['platform']}_Leak_{i}")
        else:
            prev_node = f"{pirated_clips[i-1]['platform']}_Leak_{i-1}"
            curr_node = f"{pirated_clips[i]['platform']}_Leak_{i}"
            G.add_edge(prev_node, curr_node)
            
    # Draw Graph
    plt.figure(figsize=(12, 6))
    pos = nx.spring_layout(G, seed=42, k=0.5) # Layout algorithm
    
    # Color coding
    node_colors = ['green' if n == "Original Source" else '#ff4b4b' for n in G.nodes()]
    
    nx.draw(G, pos, 
            with_labels=True, 
            node_color=node_colors, 
            font_size=10, 
            node_size=2500, 
            arrows=True, 
            arrowstyle='->', 
            arrowsize=20,
            font_weight='bold',
            edge_color='gray',
            width=2)
    
    plt.title("Content Propagation Path: From Leak to Viral Spread", fontsize=14, pad=20)
    
    # Save Image
    output_dir.mkdir(parents=True, exist_ok=True)
    graph_path = output_dir / "propagation_graph.png"
    plt.savefig(graph_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    logger.info(f"📈 Propagation Graph saved: {graph_path.name}")
    return str(graph_path)

if __name__ == "__main__":
    # --- Self Test ---
    print("🧪 Testing Action Engine...")
    root = Path(__file__).resolve().parent.parent
    test_dir = root / "test_action_output"
    
    # 1. Test DMCA
    dmca_path = generate_dmca_report("Test_Clip_01", "FAKE", "LEAKER_ID_99", test_dir)
    
    # 2. Test Graph
    spread_data = [
        {"platform": "Telegram", "time": "T+5m"},
        {"platform": "Instagram", "time": "T+20m"},
        {"platform": "YouTube", "time": "T+45m"}
    ]
    graph_path = simulate_propagation_graph("Original_Match", spread_data, test_dir)
    
    print(f"✅ Test Complete. Files saved in: {test_dir}")